### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by coding-in-public** [jsjoeio/speak-argentinian-spanish#14]
Figured we could do a quick 404 page for uncaught routes. 

Perhaps include:
- link to homepage
- CTA sign up form as well?

**Comment by jsjoeio** [comment]
Sounds great!

**Comment by coding-in-public** [comment]
Cool; I'll get something together here.

**Comment by jsjoeio** [comment]
Closed by https://github.com/jsjoeio/speak-argentinian-spanish/pull/16
