### ISSUE TITLE
Blog page changes

### ISSUE THREAD

**Issue by coding-in-public** [jsjoeio/speak-argentinian-spanish#15]
Two ideas here: 
## 1. Improve blog “main” page
- perhaps cards like the refold ones?
- ![cards](https://user-images.githubusercontent.com/86967271/234456642-6be28bdf-6f3f-445e-822c-e5226a6e6d21.png)
- perhaps make main body of the pages all white with only a blue nav bar?
- pagination? (6? posts at a time—maybe for future)
- tag cloud?
- filter?
- search?
## 2. Improve styling for post page
- perhaps make main body of the pages all white with only a blue nav bar?
- inject CTA for sign up at the bottom of each page?

**Comment by jsjoeio** [comment]
I like all those! We could skip tag cloud, filter  but keep search I think 🤔

**Comment by coding-in-public** [comment]
Okay, can do. You have a preference with search? I can build all a json output on build containing all the post descriptions, titles, etc. and then just search against that with a searching library perhaps at a /search route so people can share searches (i.e., it'd use query params). Or we can do something else?

**Comment by jsjoeio** [comment]
I like the sound of that! As long as we can have some script that will automatically update the json output when a new blog post is added (maybe in CI).

Also down to pull in a library or something to make it easier! 

My only ask is that I don't have to update something every time I add a new blog post. If that's not possible then we can skip doing search for now!

**Comment by coding-in-public** [comment]
Oh, yeah. Definitely. There's a way to generate a new JSON file each time you build, so it _should_ always be up to date. I might split the search off to its own branch and just focus on the layout for now? And then we can address search. Looking to do the 404 page today or tomorrow and perhaps the blog page(s) by the weekend or so?

**Comment by jsjoeio** [comment]
I like that. I prefer smaller changsets per PR anyway (easier to review).

Sounds like a plan! 🙌

**Comment by coding-in-public** [comment]
moved search to #25
