### ISSUE TITLE
Add Search to blog

### ISSUE THREAD

**Issue by coding-in-public** [jsjoeio/speak-argentinian-spanish#25]

**Comment by coding-in-public** [comment]
@jsjoeio My plan was to:
1. Create a dynamic JSON api endpoint
2. FuseJS to fuzzy match queries
3. /search route that uses react to fetch the api endpoint
4. Astro search widget form that redirects to the search route (i.e., /search?q=query)

You okay with this basic direction? Or prefer something else?

**Comment by jsjoeio** [comment]
Sounds great to me! 🔥

**Comment by jsjoeio** [comment]
Fixed by https://github.com/jsjoeio/speak-argentinian-spanish/pull/29
