### ISSUE TITLE
Homepage layout with new footer

### ISSUE THREAD

**Issue by coding-in-public** [jsjoeio/speak-argentinian-spanish#45]

**Comment by coding-in-public** [comment]
How's something like this work for a redesign/footer placement, @jsjoeio? 

<img width="737" alt="homepage" src="https://github.com/jsjoeio/speak-argentinian-spanish/assets/86967271/d3a5267b-2a6f-41b1-a708-02dbe93b7dd5">

**Comment by jsjoeio** [comment]
Love it!

Can we make the center part 1.5 bigger? (aka increase font sizes by 1.5x or something) 

Besides that, looks wonderful!
